language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - pypy
  - pypy3
script: 
  - python tests.py
install:
  - python setup.py install
notifications:
  email: false
